# Generated by Django 5.0.3 on 2024-04-22 11:25

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsCOE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=50)),
                ('fatherName', models.CharField(max_length=50)),
                ('rollnumber', models.IntegerField()),
                ('programme', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('mobilenumber', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('aadharnumber', models.IntegerField()),
                ('nodues_copy', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('aadharcopy', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('status', models.CharField(default='processing', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='IST time', verbose_name='Created At')),
                ('Certificate', models.CharField(max_length=50)),
                ('FIR_copy', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('newsadv', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('payment_ss', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('verified_by', models.CharField(blank=True, max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='IST time', verbose_name='Updated At')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
